### ISSUE TITLE
gcov renders travis logs useless

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-super#1]
See for instance https://travis-ci.org/dune-community/dune-xt-common/jobs/170168674. With line 4227 starts a list which is too long for anything else to be contained in the log. I have no idea what to do about it. @renemilk?

**Comment by renemilk** [comment]
You can suppress output here: https://github.com/dune-community/dune-xt-super/blob/master/.travis/yaml/template.yml#L67

**Comment by ftalbrecht** [comment]
Thx for the tip, keeping this open until I'm sure it works...

**Comment by renemilk** [comment]
Did you forget to update the template?

**Comment by ftalbrecht** [comment]
Most surely...

**Comment by renemilk** [comment]
Close?

**Comment by ftalbrecht** [comment]
Otherwise I'll open again...
