### ISSUE TITLE
remove dune-localfunctions?

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-super#11]
I just noticed this is still in here, but no other module actually references it. Is this an oversight, or did we plan something with it I forgot again, @dune-community/dune-xt-devs ?

**Comment by ftalbrecht** [comment]
As far as I can see we only require dune-localfunctions in dune-gdt.

**Comment by renefritze** [comment]
[Done](https://github.com/dune-community/dune-xt-super/commit/42cfdceb9d019c08e90b23be602fe9b8dc305a77)
