### ISSUE TITLE
New test skipping behaviour in dune-testtools cmake

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-xt-super#2]
Between 2.4 and 2.5 testtools/common switched from discarding tests with a corresponding ```cmake_guard``` to making ctest skip them. CTest however counts skipped tests as failed. 
There's a drop-in wrapper that checks ctest's output and changes its exit code accordingly: https://gitlab.dune-project.org/core/dune-common/blob/master/bin/dune-ctest
I don't really like depending on ctest output being stable between versions. And I don't want to change our CI setups to replace ctest with dune-ctest everywhere. Changing the Ctest behaviour however is a 4 year old issue. 
So I went ahead and implemented it: https://gitlab.kitware.com/cmake/cmake/merge_requests/399
In the short term I'd say we should revert the behaviour change in testtools though, since even if the cmake PR is accepted it would take a long while before we get (release) access to it.

**Comment by ftalbrecht** [comment]
So you went ahead and patched cmake... Nice! :) Apart from that: agreed.

**Comment by renemilk** [comment]
The patch and basically the issue too, was rejected. We're now using a patched version of testtools in our super modules where the changes have been reverted.
