### ISSUE TITLE
commit message turns up as evn var in docker build on travis

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-super#4]
See https://travis-ci.org/dune-community/dune-xt-grid/jobs/267729757#L593, any ideas @renemilk? This is from a pr, a multiline commit message containing `*`.

**Comment by renemilk** [comment]
The problem isn't that it turn up, but rather that ```shlex.quote``` does not do the Right Thing (:tm:) with it. I've fixed this in the current xt-grid PR already by blacklisting ```TRAVIS_COMMIT_MESSAGE```, but hadn't pushed this here (where the script lives).
